port: 80
testmode: 0
arweave:
  host: arweave.net
  port: 443
  protocol: https
  key: ''

storage:
  arweave_experiment_version_major: 1
  arweave_experiment_version_minor: 8
  arweave_gateway_url: https://arweave.net/graphql

s3:
  protocol: https
  host: fra1.digitaloceanspaces.com
  port: 443
  key: ''
  secret: ''
  bucket: pointdisk

log:
  level: info
  sendLogsTo: https://logstash.pointspace.io:12201

queue:
  url: amqp://localhost

max_concurrency: 10
arweave_upload_min_retry_time: 1
arweave_upload_max_retry_time: 5
